classdef Options < handle
    
    properties (Constant)
        
        GENERAL_RIG_SEARCH_PATH = 'GENERAL_RIG_SEARCH_PATH'
        
        GENERAL_PROTOCOL_SEARCH_PATH = 'GENERAL_PROTOCOL_SEARCH_PATH'
        
        GENERAL_SOURCE_DESCRIPTION_SEARCH_PATH = 'GENERAL_SOURCE_DESCRIPTION_SEARCH_PATH'
        
        FILE_DEFAULT_NAME = 'FILE_DEFAULT_NAME'
        
        FILE_DEFAULT_LOCATION = 'FILE_DEFAULT_LOCATION'
        
        EPOCH_GROUP_LABEL_LIST = 'EPOCH_GROUP_LABEL_LIST'
        
        SOURCE_LABEL_LIST = 'SOURCE_LABEL_LIST'
        
        KEYWORD_LIST = 'KEYWORD_LIST'
        
    end
    
end