% https://github.com/G-Node/odml-terminologies

classdef Electrophysiology < symphonyui.core.descriptions.ExperimentDescription
    
    methods
        
        function obj = Electrophysiology()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('projectName', '', ...
                'description', 'The name of the project this experiment belongs to.'), ...
                PropertyDescriptor('experimenter', '', ...
                'description', 'The name of the person conducting this experiment.'), ...
                PropertyDescriptor('type', '', ...
                'type', PropertyType('char', 'row', {'', 'intracellular', 'extracellular', 'patch clamp', 'whole cell patch', 'loose patch', 'ERG', 'EEG', 'EKG', 'EM'}), ...
                'description', 'Intracellular recording of single cell responses with sharp microelectrodes.'), ...
                PropertyDescriptor('subtype', '', ...
                'type', PropertyType('char', 'row', {'', 'single electrode', 'dual electrode', 'multi electrode'}), ...
                'description', 'Subtype of this electrophysiological experiment.'), ...
                ];
        end
        
    end
    
end

