classdef Electrophysiology < symphonyui.core.descriptions.ExperimentDescription
    
    methods
        
        function obj = Electrophysiology()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('experimenter', '', ...
                    'description', 'Who performed the experiment'), ...
                PropertyDescriptor('project', '', ...
                    'description', 'Project the experiment belongs to'), ...
                PropertyDescriptor('institution', '', ...
                    'description', 'Institution where the experiment was performed'), ...
                PropertyDescriptor('lab', '', ...
                    'description', 'Lab where experiment was performed'), ...
                PropertyDescriptor('description', '', ...
                    'description', 'General description of the experiment'), ...
                ];
        end
        
    end
    
end

