% http://precedings.nature.com/documents/1720/version/2/files/npre20091720-2.pdf

classdef Electrophysiology < symphonyui.core.descriptions.ExperimentDescription
    
    methods
        
        function obj = Electrophysiology()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('responsiblePerson', '', ...
                'description', 'The (stable) primary contact person for this data set; this could be the experimenter, lab head, line manager etc. Where responsibility rests with an institutional role (e.g. one of a number of duty officers) rather than a person, give the official name of the role rather than any one person. In all cases give affiliation and stable contact information, which consists of (i) Name, (ii) Postaladdress and (iii) Email address.'), ...
                PropertyDescriptor('experimentalContext', '', ...
                'description', 'The name of the project, study or wider investigation of which the ?experiment? is a part (if appropriate).'), ...
                PropertyDescriptor('electrophysiologyType', '', ...
                'type', PropertyType('char', 'row', {'', 'extra cellular', 'intra cellular'}), ...
                'description', 'The type of electrophysiology recording reported as ''extra cellular'' or ''intra cellular''.'), ...
                ];
        end
        
    end
    
end

