function [c, layout] = createLabeledTextField(parent, label, sizes)
    layout = uiextras.HBox( ...
        'Parent', parent, ...
        'Spacing', 7);
    SymphonyUI.Utilities.UI.createLabel(layout, label);
    c = uicontrol( ...
        'Parent', layout, ...
        'Style', 'edit', ...
        'HorizontalAlignment', 'left');
    set(layout, 'Sizes', sizes);
end