function f = desc2field(desc)
    f = uiextras.jide.PropertyGridField.empty(0, max(1, numel(desc)));
    for i = 1:numel(desc)
        d = desc(i);
        t = d.type;
        f(i) = uiextras.jide.PropertyGridField(d.name, d.value, ...
            'Type', uiextras.jide.PropertyType(t.primitiveType, t.shape, t.domain), ...
            'Category', d.category, ...
            'DisplayName', d.displayName, ...
            'Description', d.description, ...
            'ReadOnly', d.readOnly, ...
            'Hidden', d.hidden, ...
            'Preferred', d.preferred);
    end
end

