classdef DeviceBackgroundsView < symphonyui.ui.View

    events
        Apply
        Cancel
    end

    properties (Access = private)
        backgroundsLayout
        textFields
        applyButton
        cancelButton
    end

    methods

        function createUi(obj)
            import symphonyui.ui.util.*;

            set(obj.figureHandle, ...
                'Name', 'Device Backgrounds', ...
                'Position', screenCenter(260, 200), ...
                'WindowStyle', 'modal');

            mainLayout = uix.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 7);
            
            obj.backgroundsLayout = uix.VBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            
            obj.textFields = struct();

            % Apply/Cancel controls.
            controlsLayout = uix.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uix.Empty('Parent', controlsLayout);
            obj.applyButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Apply', ...
                'Callback', @(h,d)notify(obj, 'Apply'));
            obj.cancelButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Cancel', ...
                'Callback', @(h,d)notify(obj, 'Cancel'));
            set(controlsLayout, 'Widths', [-1 75 75]);

            set(mainLayout, 'Heights', [-1 25]);

            % Set OK button to appear as the default button.
            try %#ok<TRYNC>
                h = handle(obj.figureHandle);
                h.setDefaultButton(obj.applyButton);
            end
        end
        
        function addBackground(obj, name, quantity, units)
            layout = uix.HBox( ...
                'Parent', obj.backgroundsLayout, ...
                'Spacing', 7);
            symphonyui.ui.util.Label( ...
                'Parent', layout, ...
                'String', [name ' (' units '):']);
            obj.textFields.(name) = uicontrol( ...
                'Parent', layout, ...
                'Style', 'edit', ...
                'String', quantity, ...
                'HorizontalAlignment', 'left');
        end
        
        function q = getBackground(obj, name)
            q = get(obj.textFields.(name), 'String');
        end

    end

end
