classdef NewExperimentView < symphonyui.ui.View

    events
        BrowseLocation
        Open
        Cancel
    end

    properties (Access = private)
        nameField
        locationField
        purposeField
        browseLocationButton
        openButton
        cancelButton
    end

    methods

        function createUi(obj)
            import symphonyui.ui.util.*;

            set(obj.figureHandle, ...
                'Name', 'New Experiment', ...
            	'Position', screenCenter(500, 147), ...
            	'WindowStyle', 'modal');

            mainLayout = uix.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 7);

            parametersLayout = uix.Grid( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            Label( ...
                'Parent', parametersLayout, ...
                'String', 'Name:');
            Label( ...
                'Parent', parametersLayout, ...
                'String', 'Location:');
            Label( ...
                'Parent', parametersLayout, ...
                'String', 'Purpose:');
            obj.nameField = uicontrol( ...
                'Parent', parametersLayout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.locationField = uicontrol( ...
                'Parent', parametersLayout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.purposeField = uicontrol( ...
                'Parent', parametersLayout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            uix.Empty('Parent', parametersLayout);
            obj.browseLocationButton = uicontrol( ...
                'Parent', parametersLayout, ...
                'Style', 'pushbutton', ...
                'String', '...', ...
                'Callback', @(h,d)notify(obj, 'BrowseLocation'));
            uix.Empty('Parent', parametersLayout);
            set(parametersLayout, ...
                'Widths', [60 -1 25], ...
                'Heights', [25 25 25]);

            % Open/Cancel controls.
            controlsLayout = uix.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uix.Empty('Parent', controlsLayout);
            obj.openButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Open', ...
                'Callback', @(h,d)notify(obj, 'Open'));
            obj.cancelButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Cancel', ...
                'Callback', @(h,d)notify(obj, 'Cancel'));
            set(controlsLayout, 'Widths', [-1 75 75]);

            set(mainLayout, 'Heights', [-1 25]);

            % Set open button to appear as the default button.
            try %#ok<TRYNC>
                h = handle(obj.figureHandle);
                h.setDefaultButton(obj.openButton);
            end
        end

        function n = getName(obj)
            n = get(obj.nameField, 'String');
        end

        function setName(obj, n)
            set(obj.nameField, 'String', n);
        end

        function l = getLocation(obj)
            l = get(obj.locationField, 'String');
        end

        function setLocation(obj, l)
            set(obj.locationField, 'String', l);
        end
        
        function p = getPurpose(obj)
            p = get(obj.purposeField, 'String');
        end
        
        function requestPurposeFocus(obj)
            obj.update();
            uicontrol(obj.purposeField);
        end

    end

end
