classdef Cell < symphonyui.core.descriptions.SourceDescription
    
    methods
        
        function obj = Cell()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('targetType', '', ...
                    'description', 'The target cell type under investigation'), ...
                PropertyDescriptor('confirmedType', '', ...
                    'description', 'The confirmed type of the recorded cell'), ...
                PropertyDescriptor('recordingLocation', '', ...
                    'description', 'The recording location in the cell. E.g. axonal, dendritic, somatic, ...'), ...
                ];            
        end
        
    end
    
end

