% https://github.com/G-Node/odml-terminologies

classdef Cell < symphonyui.core.descriptions.SourceDescription
    
    methods
        
        function obj = Cell()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('type', '', ...
                'description', 'The type of the recorded cell. E.g. pyramidal cell.'), ...
                PropertyDescriptor('brainRegion', '', ...
                'description', 'The region the cell is located in. For example Retina, Cortex, Cerebellum etc.'), ...
                PropertyDescriptor('brainSubregion', '', ...
                'description', 'More detailed specification of the region the cell is located in. For example, if BrainRegion is "hippocampus", then the BrainSubRegion may be "CA1".'), ...
                PropertyDescriptor('layer', '', ...
                'description', 'The name of the layer. For example, layer 4 in CA1.'), ...
                PropertyDescriptor('ganglion', '', ...
                'description', 'Like the pro-, meta- and mesothoracal ganglion in invertebrates.'), ...
                PropertyDescriptor('structure', '', ...
                'description', 'The structure of the organism the cell is located in e.g. Eye, Spinal cord...'), ...
                PropertyDescriptor('recordingLocation', '', ...
                'description', 'The recording location in the cell. E.g. axonal, dendritic, somatic, ...'), ...
                PropertyDescriptor('identification', '', ...
                'description', 'How was the cell identified?'), ...
                PropertyDescriptor('restingPotential', 0, ...
                'description', 'What is the cells resting potential of the cell in mV. An indiator for the recording quality.'), ...
                PropertyDescriptor('baselineRate', 0, ...
                'description', 'For spiking cells, the spontaneous activity which might be an indicator for the cell''s health status and thus recording quality, in Hz.'), ...
                PropertyDescriptor('baselineNoise', 0, ...
                'description', 'The standard deviation of the baseline membrane potential.'), ...
                PropertyDescriptor('rheobase', 0, ...
                'description', 'The minimum current required to make the cell fire action potentials in nA.'), ...
                PropertyDescriptor('membraneCapacity', 0, ...
                'description', 'The capacity of the cell in pF.'), ...
                PropertyDescriptor('inputResistance', 0, ...
                'description', 'The input resistance of the recorded cell in MOhm'), ...
                PropertyDescriptor('timeConstant', 0, ...
                'description', 'The membrane time-constant in ms.'), ...
                PropertyDescriptor('comment', '', ...
                'description', 'A comment on the cell.'), ...
                ];            
        end
        
    end
    
end

