classdef Example < symphonyui.core.descriptions.SourceDescription
    
    methods
        
        function obj = Example()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('double', pi, ...
                    'category', 'Primitive', ...
                    'description', 'Standard MatLab type.'), ...
                PropertyDescriptor('single', pi, ...
                    'category', 'Primitive', ...
                    'description', 'Single-precision floating point number.'), ...
                PropertyDescriptor('integer', int32(23), ...
                    'category', 'Primitive', ...
                    'description', 'A 32-bit integer value.'), ...
                PropertyDescriptor('interval', int32(2), ...
                    'type', PropertyType('int32', 'scalar', [0 6]), ...
                    'category', 'Primitive', ...
                    'description', 'A 32-bit integer value with an interval domain.'), ...
                PropertyDescriptor('enumerated', int32(-1), ...
                    'type', PropertyType('int32', 'scalar', {int32(-1), int32(0), int32(1)}), ...
                    'category', 'Primitive', ...
                    'description', 'A 32-bit integer value with an enumerated domain.'), ...
                PropertyDescriptor('logical', true, ...
                    'category', 'Primitive', ...
                    'description', 'A Boolean value that takes either true or false.'), ...
                PropertyDescriptor('doublematrix', [], ...
                    'type', PropertyType('denserealdouble', 'matrix'), ...
                    'category', 'Compound', ...
                    'description', 'Matrix of standard MatLab type with empty initial value.'), ...
                PropertyDescriptor('string', 'a sample string', ...
                    'category', 'Compound', ...
                    'description', 'A row vector of characters.'), ...
                PropertyDescriptor('selection', 'spring', ...
                    'type', PropertyType('char', 'row', {'spring', 'summer', 'fall', 'winter'}), ...
                    'category', 'Compound', ...
                    'description', 'A row vector of characters that can take any of the predefined set of values.'), ...
                PropertyDescriptor('number', 1, ...
                    'type', PropertyType('denserealdouble', 'row', {1, 2, 3, 4}), ...
                    'category', 'Compound', ...
                    'description', 'A row vector of characters that can take any of the predefined set of values.'), ...
                PropertyDescriptor('set', [true false true], ...
                    'type', PropertyType('logical', 'row', {'A', 'B', 'C'}), ...
                    'category', 'Compound', ...
                    'description', 'A logical vector that serves an indicator of which elements from a universe are included in the set.'), ...
                PropertyDescriptor('date', datestr(now), ...
                    'type', PropertyType('datestr', 'row'), ...
                    'category', 'Special', ...
                    'description', 'A date string.'), ...
                ];            
        end
        
    end
    
end

