% https://github.com/G-Node/odml-terminologies

classdef Preparation < symphonyui.core.descriptions.SourceDescription
    
    methods
        
        function obj = Preparation()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('date', '', ...
                'description', 'Actual preparation date.'), ...
                PropertyDescriptor('type', '', ...
                'description', 'In vivo or in vitro?'), ...
                PropertyDescriptor('ringersSolution', '', ...
                'description', 'The Ringer solution used during preparation.'), ...
                PropertyDescriptor('slicingMethod', '', ...
                'description', 'How was the brain sliced: Microtome etc.'), ...
                PropertyDescriptor('sliceThickness', 0, ...
                'description', 'The thickness of the slice in microns.'), ...
                PropertyDescriptor('sliceOrientation', '', ...
                'description', 'The slice orientation: horizontal, sagital etc.'), ...
                PropertyDescriptor('bathSolution', '', ...
                'description', 'The solution the slice is bathed in.'), ...
                PropertyDescriptor('solutionFlowSpeed', 0, ...
                'description', 'The flow speed of the bath solution in ml/mm.'), ...
                PropertyDescriptor('bathTemperature', 0, ...
                'description', 'The temperature of the bath solution.'), ...
                PropertyDescriptor('anaestesia', false, ...
                'description', 'Is the animal under anaesthesia (true) or awake (false)?'), ...
                PropertyDescriptor('anaesthetic', '', ...
                'description', 'The drug used for anaesthesia.'), ...
                PropertyDescriptor('anaestheticDose', 0, ...
                'description', 'The dose of the used anaesthetic.'), ...
                PropertyDescriptor('localAnaesthesia', false, ...
                'description', 'Was there some local anaesthesia applied (true or false).'), ...
                PropertyDescriptor('localAnaesthetic', '', ...
                'description', 'The drug that was used for local anaesthesia.'), ...
                PropertyDescriptor('localAnaestheticDose', 0, ...
                'description', 'The dose of the used local anaesthetic.'), ...
                PropertyDescriptor('localAnaestheticLocation', '', ...
                'description', 'Describes the place the local anaesthetic was applied.'), ...
                ];            
        end
        
    end
    
end

