classdef Preparation < symphonyui.core.descriptions.SourceDescription
    
    methods
        
        function obj = Preparation()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('protocol', '', ...
                    'description', 'The preparation protocol implemented to obtain the specific sample'), ...
                PropertyDescriptor('date', '', ...
                    'description', 'The date the preparation protocol was performed to obtain the specific sample'), ...
                PropertyDescriptor('region', ''), ...
                PropertyDescriptor('sliceThickness', 0, ...
                    'description', 'The thickness of the slice in microns'), ...
                PropertyDescriptor('sliceOrientation', '', ...
                    'description', 'The slice orientation: horizontal, sagital etc'), ...
                PropertyDescriptor('bathTemperature', 0, ...
                    'description', 'The temperature of the bath solution'), ...
                PropertyDescriptor('bathSolution', '', ...
                    'description', 'The solution the slice is bathed in'), ...
                ];            
        end
        
    end
    
end

