classdef Subject < symphonyui.core.descriptions.SourceDescription
    
    methods
        
        function obj = Subject()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('id', '', ...
                    'description', 'ID of animal/person (lab convention)'), ...
                PropertyDescriptor('description', '', ...
                    'description', 'Description of subject and where subject came from (eg, breeder, if animal)'), ...
                PropertyDescriptor('species', '', ...
                    'description', 'Species'), ...
                PropertyDescriptor('genotype', '', ...
                    'description', 'Genetic strain'), ...
                PropertyDescriptor('sex', '', ...
                    'type', PropertyType('char', 'row', {'', 'male', 'female', 'hermaphrodite'}), ...
                    'description', 'Gender of the subject'), ...
                PropertyDescriptor('age', '', ...
                    'description', 'Age of person, animal, embryo'), ...
                PropertyDescriptor('weight', '', ...
                    'description', 'Weight at time of experiment, at time of surgery, and at other important times'), ...
                ];            
        end
        
    end
    
end

