% https://github.com/G-Node/odml-terminologies

classdef Subject < symphonyui.core.descriptions.SourceDescription
    
    methods
        
        function obj = Subject()
            import symphonyui.core.*;
            
            obj.propertyDescriptors = [ ...
                PropertyDescriptor('comment', '', ...
                'description', 'A general comment on a specific subject.'), ...
                PropertyDescriptor('species', '', ...
                'description', 'The scientific name of the species e.g. Apis mellifera, Homo sapiens.'), ...
                PropertyDescriptor('genus', '', ...
                'description', 'The genus of the studied subject.'), ...
                PropertyDescriptor('trivialName', '', ...
                'description', 'The trivial name of the species like Honeybee, Human.'), ...
                PropertyDescriptor('gender', '', ...
                'type', PropertyType('char', 'row', {'', 'male', 'female', 'hermaphrodite'}), ...
                'description', 'The gender of the subject.'), ...
                PropertyDescriptor('age', '', ...
                'description', 'The age of the subject since birth. E.g. P19, or 5 days.'), ...
                PropertyDescriptor('strain', '', ...
                'description', 'The strain the subject was taken from. E.g. a specific genetic variation etc.'), ...
                PropertyDescriptor('cellLine', '', ...
                'description', 'The identifier for the immortalized cell line.'), ...
                PropertyDescriptor('population', '', ...
                'description', 'The population this subject is offspring of. This may be the bee hive, the ant colony, etc.'), ...
                PropertyDescriptor('healthStatus', '', ...
                'description', 'Information about the health status of this subject.'), ...
                PropertyDescriptor('developmentalStage', '', ...
                'description', 'The developemtal stage of the subject. E.g. "embroyonal", "adult", "larval" etc.'), ...
                PropertyDescriptor('size', 0, ...
                'description', 'The size of the subject. This value may be used context dependent. Size could be length for a fish, heigth for a human subject, or shoulder height for a horse etc...'), ...
                PropertyDescriptor('weight', 0, ...
                'description', 'The weight of this subject.'), ...
                ];            
        end
        
    end
    
end

