classdef Settings < handle
    
    properties (Constant)
        
        GENERAL_RIG_SEARCH_PATH = 'GENERAL_RIG_SEARCH_PATH'
        
        GENERAL_PROTOCOL_SEARCH_PATH = 'GENERAL_PROTOCOL_SEARCH_PATH'
        
        EXPERIMENT_DEFAULT_NAME = 'EXPERIMENT_DEFAULT_NAME'
        
        EXPERIMENT_DEFAULT_LOCATION = 'EXPERIMENT_DEFAULT_LOCATION'
        
        EPOCH_GROUP_LABEL_LIST = 'EPOCH_GROUP_LABEL_LIST'
        
        SOURCE_LABEL_LIST = 'SOURCE_LABEL_LIST'
        
    end
    
end