classdef AddConfigurationSettingView < appbox.View

    events
        Add
        Cancel
    end

    properties (Access = private)
        keyField
        valueField
        addButton
        cancelButton
    end

    methods

        function createUi(obj)
            import appbox.*;

            set(obj.figureHandle, ...
                'Name', 'Add Configuration Setting', ...
                'Position', screenCenter(250, 109), ...
                'Resize', 'off');

            mainLayout = uix.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 11);

            propertyLayout = uix.Grid( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            Label( ...
                'Parent', propertyLayout, ...
                'String', 'Key:');
            Label( ...
                'Parent', propertyLayout, ...
                'String', 'Value:');
            obj.keyField = uicontrol( ...
                'Parent', propertyLayout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.valueField = uicontrol( ...
                'Parent', propertyLayout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            set(propertyLayout, ...
                'Widths', [40 -1], ...
                'Heights', [23 23]);

            % Add/Cancel controls.
            controlsLayout = uix.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uix.Empty('Parent', controlsLayout);
            obj.addButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Add', ...
                'Interruptible', 'off', ...
                'Callback', @(h,d)notify(obj, 'Add'));
            obj.cancelButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Cancel', ...
                'Interruptible', 'off', ...
                'Callback', @(h,d)notify(obj, 'Cancel'));
            set(controlsLayout, 'Widths', [-1 75 75]);

            set(mainLayout, 'Heights', [-1 23]);

            % Set add button to appear as the default button.
            try %#ok<TRYNC>
                h = handle(obj.figureHandle);
                h.setDefaultButton(obj.addButton);
            end
        end

        function k = getKey(obj)
            k = get(obj.keyField, 'String');
        end

        function requestKeyFocus(obj)
            obj.update();
            uicontrol(obj.keyField);
        end

        function v = getValue(obj)
            v = get(obj.valueField, 'String');
        end

    end

end
