classdef AddEntityPresetView < appbox.View

    events
        Add
        Cancel
    end

    properties (Access = private)
        nameField
        entityTypeField
        descriptionTypeField
        addButton
        cancelButton
    end

    methods

        function createUi(obj)
            import appbox.*;

            set(obj.figureHandle, ...
                'Name', 'Add Entity Preset', ...
                'Position', screenCenter(450, 139));

            mainLayout = uix.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 11);

            propertyLayout = uix.Grid( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            Label( ...
                'Parent', propertyLayout, ...
                'String', 'Name:');
            Label( ...
                'Parent', propertyLayout, ...
                'String', 'Entity type:');
            Label( ...
                'Parent', propertyLayout, ...
                'String', 'Description type:');
            obj.nameField = uicontrol( ...
                'Parent', propertyLayout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.entityTypeField = uicontrol( ...
                'Parent', propertyLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            obj.descriptionTypeField = uicontrol( ...
                'Parent', propertyLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            set(propertyLayout, ...
                'Widths', [90 -1], ...
                'Heights', [23 23 23]);

            % Add/Cancel controls.
            controlsLayout = uix.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uix.Empty('Parent', controlsLayout);
            obj.addButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Add', ...
                'Interruptible', 'off', ...
                'Callback', @(h,d)notify(obj, 'Add'));
            obj.cancelButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Cancel', ...
                'Interruptible', 'off', ...
                'Callback', @(h,d)notify(obj, 'Cancel'));
            set(controlsLayout, 'Widths', [-1 75 75]);

            set(mainLayout, 'Heights', [-1 23]);

            % Set add button to appear as the default button.
            try %#ok<TRYNC>
                h = handle(obj.figureHandle);
                h.setDefaultButton(obj.addButton);
            end
        end

        function n = getName(obj)
            n = get(obj.nameField, 'String');
        end

        function requestNameFocus(obj)
            obj.update();
            uicontrol(obj.nameField);
        end
        
        function setEntityType(obj, t)
            set(obj.entityTypeField, 'String', t);
        end
        
        function setDescriptionType(obj, t)
            set(obj.descriptionTypeField, 'String', t);
        end

    end

end

