classdef AddProtocolPresetView < appbox.View

    events
        Add
        Cancel
    end

    properties (Access = private)
        nameField
        protocolIdField
        addButton
        cancelButton
    end

    methods

        function createUi(obj)
            import appbox.*;

            set(obj.figureHandle, ...
                'Name', 'Add Protocol Preset', ...
                'Position', screenCenter(360, 109), ...
                'Resize', 'off');

            mainLayout = uix.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 11);

            presetLayout = uix.Grid( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            Label( ...
                'Parent', presetLayout, ...
                'String', 'Name:');
            Label( ...
                'Parent', presetLayout, ...
                'String', 'Protocol ID:');
            obj.nameField = uicontrol( ...
                'Parent', presetLayout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.protocolIdField = uicontrol( ...
                'Parent', presetLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            set(presetLayout, ...
                'Widths', [65 -1], ...
                'Heights', [23 23]);

            % Add/Cancel controls.
            controlsLayout = uix.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uix.Empty('Parent', controlsLayout);
            obj.addButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Add', ...
                'Interruptible', 'off', ...
                'Callback', @(h,d)notify(obj, 'Add'));
            obj.cancelButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Cancel', ...
                'Interruptible', 'off', ...
                'Callback', @(h,d)notify(obj, 'Cancel'));
            set(controlsLayout, 'Widths', [-1 75 75]);

            set(mainLayout, 'Heights', [-1 23]);

            % Set add button to appear as the default button.
            try %#ok<TRYNC>
                h = handle(obj.figureHandle);
                h.setDefaultButton(obj.addButton);
            end
        end

        function n = getName(obj)
            n = get(obj.nameField, 'String');
        end

        function requestNameFocus(obj)
            obj.update();
            uicontrol(obj.nameField);
        end

        function setProtocolId(obj, i)
            set(obj.protocolIdField, 'String', i);
        end

    end

end

