classdef DataManagerView < symphonyui.ui.View

    events
        BeginEpochGroup
        EndEpochGroup
        AddSource
        SelectedNodes
        AddProperty
        RemoveProperty
        AddKeyword
        RemoveKeyword
        AddNote
        RemoveNote
    end

    properties (Access = private)
        beginEpochGroupTool
        endEpochGroupTool
        addSourceTool
        experimentTree
        devicesRootNode
        sourcesRootNode
        epochGroupsRootNode
        tabGroup
        dataCardPanel
        emptyCard
        deviceCard
        sourceCard
        experimentCard
        epochGroupCard
        epochCard
        propertiesTable
        keywordsTable
        notesTable
    end

    properties (Constant)
        EMPTY_DATA_CARD          = 1
        DEVICE_DATA_CARD         = 2
        SOURCE_DATA_CARD         = 3
        EXPERIMENT_DATA_CARD     = 4
        EPOCH_GROUP_DATA_CARD    = 5
        EPOCH_DATA_CARD          = 6
    end

    methods

        function createUi(obj)
            import symphonyui.ui.util.*;

            set(obj.figureHandle, 'Name', 'Data Manager');
            set(obj.figureHandle, 'Position', screenCenter(559, 350));

            % Toolbar.
            toolbar = uitoolbar( ...
                'Parent', obj.figureHandle);
            obj.beginEpochGroupTool = uipushtool( ...
                'Parent', toolbar, ...
                'TooltipString', 'Begin Epoch Group...', ...
                'ClickedCallback', @(h,d)notify(obj, 'BeginEpochGroup'));
            setIconImage(obj.beginEpochGroupTool, symphonyui.app.App.getResource('icons/group_begin.png'));
            obj.endEpochGroupTool = uipushtool( ...
                'Parent', toolbar, ...
                'TooltipString', 'End Epoch Group', ...
                'ClickedCallback', @(h,d)notify(obj, 'EndEpochGroup'));
            setIconImage(obj.endEpochGroupTool, symphonyui.app.App.getResource('icons/group_end.png'));
            obj.addSourceTool = uipushtool( ...
                'Parent', toolbar, ...
                'TooltipString', 'Add Source...', ...
                'Separator', 'on', ...
                'ClickedCallback', @(h,d)notify(obj, 'AddSource'));
            setIconImage(obj.addSourceTool, symphonyui.app.App.getResource('icons/source_add.png'));

            mainLayout = uix.HBoxFlex( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 7);

            masterLayout = uix.VBoxFlex( ...
                'Parent', mainLayout, ...
                'Spacing', 7);

            obj.experimentTree = uiextras.jTree.Tree( ...
                'Parent', masterLayout, ...
                'FontName', get(obj.figureHandle, 'DefaultUicontrolFontName'), ...
                'FontSize', get(obj.figureHandle, 'DefaultUicontrolFontSize'), ...
                'SelectionChangeFcn', @(h,d)notify(obj, 'SelectedNodes'), ...
                'SelectionType', 'discontiguous');
            root = obj.experimentTree.Root;
            root.setIcon(symphonyui.app.App.getResource('icons/experiment.png'));
            
            devices = uiextras.jTree.TreeNode( ...
                'Parent', root, ...
                'Name', 'Devices');
            devices.setIcon(symphonyui.app.App.getResource('icons/folder.png'));
            obj.devicesRootNode = devices;

            sources = uiextras.jTree.TreeNode( ...
                'Parent', root, ...
                'Name', 'Sources');
            sources.setIcon(symphonyui.app.App.getResource('icons/folder.png'));
            obj.sourcesRootNode = sources;

            groups = uiextras.jTree.TreeNode( ...
                'Parent', root, ...
                'Name', 'Epoch Groups');
            groups.setIcon(symphonyui.app.App.getResource('icons/folder.png'));
            obj.epochGroupsRootNode = groups;

            detailLayout = uix.VBox( ...
                'Parent', mainLayout);

            % Tab panel.
            obj.tabGroup = uitabgroup( ...
                'Parent', detailLayout);
            
            % Data tab.
            dataTab = uitab( ...
                'Parent', obj.tabGroup, ...
                'Title', 'Data');
            
            obj.dataCardPanel = uix.CardPanel( ...
                'Parent', dataTab);
            
            % Empty card.
            emptyLayout = uix.VBox('Parent', obj.dataCardPanel); %#ok<NASGU>
            
            % Device card.
            deviceLayout = uix.Grid( ...
                'Parent', obj.dataCardPanel, ...
                'Padding', 11, ...
                'Spacing', 7);
            Label( ...
                'Parent', deviceLayout, ...
                'String', 'Name:');
            Label( ...
                'Parent', deviceLayout, ...
                'String', 'Manufacturer:');
            obj.deviceCard.nameField = uicontrol( ...
                'Parent', deviceLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            obj.deviceCard.manufacturerField = uicontrol( ...
                'Parent', deviceLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            set(deviceLayout, ...
                'Widths', [60 -1], ...
                'Heights', [25 25]);
            
            % Source card.
            sourceLayout = uix.Grid( ...
                'Parent', obj.dataCardPanel, ...
                'Padding', 11, ...
                'Spacing', 7);
            Label( ...
                'Parent', sourceLayout, ...
                'String', 'Label:');
            obj.sourceCard.labelField = uicontrol( ...
                'Parent', sourceLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            set(sourceLayout, ...
                'Widths', [60 -1], ...
                'Heights', [25]);

            % Experiment card.
            experimentLayout = uix.Grid( ...
                'Parent', obj.dataCardPanel, ...
                'Padding', 11, ...
                'Spacing', 7);
            Label( ...
                'Parent', experimentLayout, ...
                'String', 'Purpose:');
            Label( ...
                'Parent', experimentLayout, ...
                'String', 'Start time:');
            Label( ...
                'Parent', experimentLayout, ...
                'String', 'End time:');
            obj.experimentCard.purposeField = uicontrol( ...
                'Parent', experimentLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            obj.experimentCard.startTimeField = uicontrol( ...
                'Parent', experimentLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            obj.experimentCard.endTimeField = uicontrol( ...
                'Parent', experimentLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            set(experimentLayout, ...
                'Widths', [60 -1], ...
                'Heights', [25 25 25]);

            % Epoch group card.
            epochGroupLayout = uix.Grid( ...
                'Parent', obj.dataCardPanel, ...
                'Padding', 11, ...
                'Spacing', 7);
            Label( ...
                'Parent', epochGroupLayout, ...
                'String', 'Label:');
            Label( ...
                'Parent', epochGroupLayout, ...
                'String', 'Start time:');
            Label( ...
                'Parent', epochGroupLayout, ...
                'String', 'End time:');
            Label( ...
                'Parent', epochGroupLayout, ...
                'String', 'Source:');
            obj.epochGroupCard.labelField = uicontrol( ...
                'Parent', epochGroupLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            obj.epochGroupCard.startTimeField = uicontrol( ...
                'Parent', epochGroupLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            obj.epochGroupCard.endTimeField = uicontrol( ...
                'Parent', epochGroupLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            obj.epochGroupCard.sourceField = uicontrol( ...
                'Parent', epochGroupLayout, ...
                'Style', 'edit', ...
                'Enable', 'off', ...
                'HorizontalAlignment', 'left');
            set(epochGroupLayout, ...
                'Widths', [60 -1], ...
                'Heights', [25 25 25 25]);
            
            set(obj.dataCardPanel, 'Selection', 1);

            % Epoch card.
            epochLayout = uix.VBox( ...
                'Parent', obj.dataCardPanel, ...
                'Spacing', 7);
            obj.epochCard.tabGroupParent = uix.Panel('Parent', epochLayout, 'BorderType', 'none');
            set(epochLayout, 'Heights', [-1]);

            % Properties tab.
            propertiesTab = uitab( ...
                'Parent', obj.tabGroup, ...
                'Title', 'Properties');
            propertiesLayout = uix.VBox( ...
                'Parent', propertiesTab);
            obj.propertiesTable = Table( ...
                'Parent', propertiesLayout, ...
                'ColumnName', {'Key', 'Value'}, ...
                'Enable', 'off');
            obj.createAddRemoveButtons(propertiesLayout, @(h,d)notify(obj, 'AddProperty'), @(h,d)notify(obj, 'RemoveProperty'));
            set(propertiesLayout, 'Heights', [-1 25]);

            % Keywords tab.
            keywordsTab = uitab( ...
                'Parent', obj.tabGroup, ...
                'Title', 'Keywords');
            keywordsLayout = uix.VBox( ...
                'Parent', keywordsTab);
            obj.keywordsTable = Table( ...
                'Parent', keywordsLayout, ...
                'ColumnName', {'Keywords'}, ...
                'Enable', 'off');
            obj.createAddRemoveButtons(keywordsLayout, @(h,d)notify(obj, 'AddKeyword'), @(h,d)notify(obj, 'RemoveKeyword'));
            set(keywordsLayout, 'Heights', [-1 25]);

            % Notes tab.
            notesTab = uitab( ...
                'Parent', obj.tabGroup, ...
                'Title', 'Notes');
            notesLayout = uix.VBox( ...
                'Parent', notesTab);
            obj.notesTable = Table( ...
                'Parent', notesLayout, ...
                'ColumnName', {'Time', 'Text'}, ...
                'ColumnWidth', {80}, ...
                'Enable', 'off');
            [~, removeButton] = obj.createAddRemoveButtons(notesLayout, @(h,d)notify(obj, 'AddNote'), @(h,d)notify(obj, 'RemoveNote'));
            set(removeButton, 'Enable', 'off');
            set(notesLayout, 'Heights', [-1 25]);

            set(mainLayout, 'Widths', [-1 -2]);
        end

        function enableBeginEpochGroup(obj, tf)
            set(obj.beginEpochGroupTool, 'Enable', symphonyui.ui.util.onOff(tf));
        end

        function enableEndEpochGroup(obj, tf)
            set(obj.endEpochGroupTool, 'Enable', symphonyui.ui.util.onOff(tf));
        end

        function setSelectedDataCard(obj, index)
            set(obj.dataCardPanel, 'Selection', index);
        end
        
        function n = getDevicesRootNode(obj)
            n = obj.devicesRootNode;
        end

        function n = addDeviceNode(obj, parent, name, value)
            n = uiextras.jTree.TreeNode( ...
                'Parent', parent, ...
                'Name', name, ...
                'Value', value);
            n.setIcon(symphonyui.app.App.getResource('icons/device.png'));
        end

        function setDeviceName(obj, n)
            set(obj.deviceCard.nameField, 'String', n);
        end
        
        function setDeviceManufacturer(obj, m)
            set(obj.deviceCard.manufacturerField, 'String', m);
        end
        
        function n = getSourcesRootNode(obj)
            n = obj.sourcesRootNode;
        end

        function n = addSourceNode(obj, parent, name, value)
            n = uiextras.jTree.TreeNode( ...
                'Parent', parent, ...
                'Name', name, ...
                'Value', value);
            n.setIcon(symphonyui.app.App.getResource('icons/source.png'));
        end

        function setSourceLabel(obj, l)
            set(obj.sourceCard.labelField, 'String', l);
        end

        function setExperimentNode(obj, name, value)
            set(obj.experimentTree.Root, ...
                'Name', name, ...
                'Value', value);
        end
        
        function n = getExperimentNode(obj)
            n = obj.experimentTree.Root;
        end

        function setExperimentPurpose(obj, p)
            set(obj.experimentCard.purposeField, 'String', p);
        end
        
        function setExperimentStartTime(obj, t)
            set(obj.experimentCard.startTimeField, 'String', datestr(t, 14));
        end
        
        function setExperimentEndTime(obj, t)
            set(obj.experimentCard.endTimeField, 'String', datestr(t, 14));
        end
        
        function n = getEpochGroupsRootNode(obj)
            n = obj.epochGroupsRootNode;
        end

        function n = addEpochGroupNode(obj, parent, name, value)
            n = uiextras.jTree.TreeNode( ...
                'Parent', parent, ...
                'Name', name, ...
                'Value', value);
            n.setIcon(symphonyui.app.App.getResource('icons/group.png'));
        end

        function setEpochGroupLabel(obj, l)
            set(obj.epochGroupCard.labelField, 'String', l);
        end

        function setEpochGroupStartTime(obj, t)
            set(obj.epochGroupCard.startTimeField, 'String', datestr(t, 14));
        end

        function setEpochGroupEndTime(obj, t)
            set(obj.epochGroupCard.endTimeField, 'String', datestr(t, 14));
        end

        function setEpochGroupSource(obj, s)
            set(obj.epochGroupCard.sourceField, 'String', s);
        end

        function setEpochGroupNodeCurrent(obj, node)
            node.setIcon(symphonyui.app.App.getResource('icons/group_current.png'));
        end

        function setEpochGroupNodeNormal(obj, node)
            node.setIcon(symphonyui.app.App.getResource('icons/group.png'));
        end

        function n = addEpochNode(obj, parent, name, value)
            n = uiextras.jTree.TreeNode( ...
                'Parent', parent, ...
                'Name', name, ...
                'Value', value);
            n.setIcon(symphonyui.app.App.getResource('icons/epoch.png'));
        end

        function collapseNode(obj, node)
            node.collapse();
        end

        function expandNode(obj, node)
            node.expand();
        end

        function nodes = getSelectedNodes(obj)
            nodes = obj.experimentTree.SelectedNodes;
        end

        function setSelectedNodes(obj, nodes)
            obj.experimentTree.SelectedNodes = nodes;
        end

        function setProperties(obj, data)
            set(obj.propertiesTable, 'Data', data);
        end

        function addProperty(obj, key, value)
            obj.propertiesTable.addRow({key, value});
        end

        function removeProperty(obj, property)
            properties = obj.propertiesTable.getColumnData(1);
            index = find(cellfun(@(c)strcmp(c, property), properties));
            obj.propertiesTable.removeRow(index); %#ok<FNDSB>
        end

        function p = getSelectedProperty(obj)
            row = get(obj.propertiesTable, 'SelectedRow');
            p = obj.propertiesTable.getValueAt(row, 1);
        end

        function setKeywords(obj, data)
            set(obj.keywordsTable, 'Data', data);
        end

        function addKeyword(obj, keyword)
            obj.keywordsTable.addRow(keyword);
        end

        function removeKeyword(obj, keyword)
            keywords = obj.keywordsTable.getColumnData(1);
            index = find(cellfun(@(c)strcmp(c, keyword), keywords));
            obj.keywordsTable.removeRow(index); %#ok<FNDSB>
        end

        function k = getSelectedKeyword(obj)
            row = get(obj.keywordsTable, 'SelectedRow');
            k = obj.keywordsTable.getValueAt(row, 1);
        end

        function setNotes(obj, data)
            set(obj.notesTable, 'Data', data);
        end

        function addNote(obj, date, text)
            obj.notesTable.addRow({date, text});
        end

    end

    methods (Access = private)

        function [addButton, removeButton] = createAddRemoveButtons(obj, parent, addCallback, removeCallback)
            layout = uix.HBox( ...
                'Parent', parent, ...
                'Spacing', 0);
            uix.Empty('Parent', layout);
            addButton = uicontrol( ...
                'Parent', layout, ...
                'Style', 'pushbutton', ...
                'String', '+', ...
                'FontSize', get(obj.figureHandle, 'DefaultUicontrolFontSize') + 1, ...
                'Callback', addCallback);
            removeButton = uicontrol( ...
                'Parent', layout, ...
                'Style', 'pushbutton', ...
                'String', '-', ...
                'FontSize', get(obj.figureHandle, 'DefaultUicontrolFontSize') + 1, ...
                'Callback', removeCallback);
            set(layout, 'Widths', [-1 25 25]);
        end

    end

end
