classdef OptionsView < symphonyui.ui.View

    events
        SelectedNode
        AddSearchPath
        RemoveSearchPath
        Apply
        Cancel
    end

    properties (Access = private)
        masterList
        detailCardPanel
        fileCard
        searchPathCard
        loggingCard
        applyButton
        cancelButton
    end

    methods

        function createUi(obj)
            import symphonyui.ui.util.*;

            set(obj.figureHandle, ...
                'Name', 'Options', ...
                'Position', screenCenter(500, 242));

            mainLayout = uix.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 7);
            
            optionsLayout = uix.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 6);
            
            masterLayout = uix.VBox( ...
                'Parent', optionsLayout, ...
                'Padding', 1);

            obj.masterList = uicontrol( ...
                'Parent', masterLayout, ...
                'Style', 'list', ...
                'String', {'File', 'Search Path', 'Logging'}, ...
                'Callback', @(h,d)notify(obj, 'SelectedNode'));
            
            detailLayout = uix.VBox( ...
                'Parent', optionsLayout, ...
                'Padding', 1);
            
            obj.detailCardPanel = uix.CardPanel( ...
                'Parent', detailLayout);
            
            % File card.
            fileGrid = uix.Grid( ...
                'Parent', obj.detailCardPanel, ...
                'Spacing', 7);
            Label( ...
                'Parent', fileGrid, ...
                'String', 'Default name:');
            Label( ...
                'Parent', fileGrid, ...
                'String', 'Default location:');
            obj.fileCard.defaultNameField = uicontrol( ...
                'Parent', fileGrid, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.fileCard.defaultLocationField = uicontrol( ...
                'Parent', fileGrid, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            set(fileGrid, ...
                'Widths', [90 -1], ...
                'Heights', [25 25]);
            
            % Search path card.
            searchPathLayout = uix.VBox( ...
                'Parent', obj.detailCardPanel, ...
                'Spacing', 7);
            obj.searchPathCard.list = ListBox( ...
                'Parent', searchPathLayout, ...
                'Style', 'list');
            searchPathMenu = uicontextmenu('Parent', obj.figureHandle);
            uimenu( ...
                'Parent', searchPathMenu, ...
                'Label', 'Add...', ...
                'Callback', @(h,d)notify(obj, 'AddSearchPath'));
            uimenu( ...
                'Parent', searchPathMenu, ...
                'Label', 'Remove', ...
                'Callback', @(h,d)notify(obj, 'RemoveSearchPath'));
            set(obj.searchPathCard.list, 'UIContextMenu', searchPathMenu);
            
            % Logging card.
            loggingGrid = uix.Grid( ...
                'Parent', obj.detailCardPanel, ...
                'Spacing', 7);
            Label( ...
                'Parent', loggingGrid, ...
                'String', 'Configuration file:');
            Label( ...
                'Parent', loggingGrid, ...
                'String', 'Log directory:');
            obj.loggingCard.configurationFileField = uicontrol( ...
                'Parent', loggingGrid, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.loggingCard.logDirectoryField = uicontrol( ...
                'Parent', loggingGrid, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            set(loggingGrid, ...
                'Widths', [100 -1], ...
                'Heights', [25 25]);
            
            set(obj.detailCardPanel, 'Selection', 1);
            
            set(optionsLayout, 'Widths', [120 -1]);

            % Apply/Cancel controls.
            controlsLayout = uiextras.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uiextras.Empty('Parent', controlsLayout);
            obj.applyButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Apply', ...
                'Interruptible', 'off', ...
                'Callback', @(h,d)notify(obj, 'Apply'));
            obj.cancelButton = uicontrol( ...
                'Parent', controlsLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Cancel', ...
                'Interruptible', 'off', ...
                'Callback', @(h,d)notify(obj, 'Cancel'));
            set(controlsLayout, 'Sizes', [-1 75 75]);

            set(mainLayout, 'Heights', [-1 25]);

            % Set OK button to appear as the default button.
            try %#ok<TRYNC>
                h = handle(obj.figureHandle);
                h.setDefaultButton(obj.applyButton);
            end
        end

        function i = getSelectedNode(obj)
            i = get(obj.masterList, 'Value');
        end

        function setCardSelection(obj, index)
            set(obj.detailCardPanel, 'Selection', index);
        end
        
        function n = getFileDefaultName(obj)
            n = get(obj.fileCard.defaultNameField, 'String');
        end
        
        function setFileDefaultName(obj, n)
            set(obj.fileCard.defaultNameField, 'String', n);
        end
        
        function n = getFileDefaultLocation(obj)
            n = get(obj.fileCard.defaultLocationField, 'String');
        end
        
        function setFileDefaultLocation(obj, l)
            set(obj.fileCard.defaultLocationField, 'String', l);
        end
        
        function i = getSelectedSearchPath(obj)
            i = get(obj.searchPathCard.list, 'Value');
        end
        
        function p = getSearchPaths(obj)
            p = get(obj.searchPathCard.list, 'String');
        end
        
        function addSearchPath(obj, path)
            s = get(obj.searchPathCard.list, 'String');
            s = [s; {path}];
            set(obj.searchPathCard.list, 'String', s);
        end
        
        function removeSearchPath(obj, index)
            s = get(obj.searchPathCard.list, 'String');
            s(index) = [];
            set(obj.searchPathCard.list, 'String', s);
        end
        
        function f = getLoggingConfigurationFile(obj)
            f = get(obj.loggingCard.configurationFileField, 'String');
        end
        
        function setLoggingConfigurationFile(obj, f)
            set(obj.loggingCard.configurationFileField, 'String', f);
        end
        
        function d = getLoggingLogDirectory(obj)
            d = get(obj.loggingCard.logDirectoryField, 'String');
        end
        
        function setLoggingLogDirectory(obj, d)
            set(obj.loggingCard.logDirectoryField, 'String', d);
        end

    end

end
