function [grid, addButton, removeButton] = createLabeledPropertyGrid(parent, label, sizes)
    layout = uiextras.VBox( ...
        'Parent', parent, ...
        'Spacing', 7);

    l = uiextras.HBox( ...
        'Parent', layout, ...
        'Spacing', 7);
    symphonyui.ui.util.createLabel(l, label);
    grid = uiextras.jide.PropertyGrid(l);
    set(l, 'Sizes', sizes);

    l = uiextras.HBox( ...
        'Parent', layout, ...
        'Spacing', 7);
    uiextras.Empty('Parent', l);
    addButton = uicontrol( ...
        'Parent', l, ...
        'Style', 'pushbutton', ...
        'String', 'Add');
    removeButton = uicontrol( ...
        'Parent', l, ...
        'Style', 'pushbutton', ...
        'String', 'Remove');
    set(l, 'Sizes', [-1 75 75]);

    set(layout, 'Sizes', [-1 25]);
end
