function [c, b, layout] = createLabeledTextFieldWithButton(parent, label, labelSize, callback, varargin)
    layout = uiextras.HBox( ...
        'Parent', parent, ...
        'Spacing', 7);
    symphonyui.ui.util.createLabel(layout, label);
    c = uicontrol( ...
        'Parent', layout, ...
        'Style', 'edit', ...
        'HorizontalAlignment', 'left', ...
        varargin{:});
    b = uicontrol( ...
        'Parent', layout, ...
        'Style', 'pushbutton', ...
        'String', '...', ...
        'Callback', callback);
    set(layout, 'Sizes', [labelSize -1 30]);
end