function [c, layout] = createLabeledTextField(parent, label, labelSize, varargin)
    layout = uiextras.HBox( ...
        'Parent', parent, ...
        'Spacing', 7);
    symphonyui.ui.util.createLabel(layout, label);
    c = uicontrol( ...
        'Parent', layout, ...
        'Style', 'edit', ...
        'HorizontalAlignment', 'left', ...
        varargin{:});
    set(layout, 'Sizes', [labelSize -1]);
end