classdef BeginEpochGroupView < SymphonyUI.Dialog
    
    properties
        controls
        epochGroup
    end
    
    methods
        
        function obj = BeginEpochGroupView()
            obj = obj@SymphonyUI.Dialog(SymphonyUI.Presenters.BeginEpochGroupPresenter());
        end
        
        function createInterface(obj)
            import SymphonyUI.Utilities.*;
            
            clf(obj.figureHandle);
            
            p = obj.presenter;
            
            set(obj.figureHandle, 'Name', 'Begin Epoch Group');
            set(obj.figureHandle, 'WindowStyle', 'modal');
            set(obj.figureHandle, 'WindowKeyPressFcn', @p.onWindowKeyPress);
            
            mainLayout = uiextras.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 7);
            
            parametersLayout = uiextras.VBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.labelText = uitext(layout, 'Label:');
            obj.controls.labelEdit = uicontrol( ...
                'Parent', layout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            set(layout, 'Sizes', [60 -1]);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.recordingText = uitext(layout, 'Recording:');
            obj.controls.recordingPopup = uicontrol( ...
                'Parent', layout, ...
                'Style', 'popupmenu', ...
                'String', {'Extracellular', 'Whole-cell', 'Suction'}, ...
                'HorizontalAlignment', 'left');
            set(layout, 'Sizes', [60 -1]);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.keywordsText = uitext(layout, 'Keywords:');
            obj.controls.keywordsEdit = uicontrol( ...
                'Parent', layout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            set(layout, 'Sizes', [60 -1]);
            
            obj.controls.propertiesPanel = uix.TabPanel( ...
                'Parent', parametersLayout, ...
                'TabWidth', 100, ...
                'FontName', get(obj.figureHandle, 'DefaultUicontrolFontName'), ...
                'FontSize', get(obj.figureHandle, 'DefaultUicontrolFontSize'));
            layout = uiextras.HBox( ...
                'Parent', obj.controls.propertiesPanel, ...
                'Padding', 11, ...
                'Spacing', 7, ...
                'BackgroundColor', [238/255 238/255 238/255]);
            vbox = uiextras.VBox( ...
                'Parent', layout);
            uitext(vbox, 'Available:');
            obj.controls.externalSolution.available = uicontrol( ...
                'Parent', vbox, ...
                'Style', 'listbox');
            set(vbox, 'Sizes', [25 -1]);
            vbox = uiextras.VBox( ...
                'Parent', layout);
            vbox = uiextras.VBox( ...
                'Parent', layout);
            uitext(vbox, 'Components:');
            obj.controls.externalSolution.components = uicontrol( ...
                'Parent', vbox, ...
                'Style', 'listbox');
            set(vbox, 'Sizes', [25 -1]);
            uiextras.Empty('Parent', obj.controls.propertiesPanel);
            uiextras.Empty('Parent', obj.controls.propertiesPanel);
            set(obj.controls.propertiesPanel, 'TabTitles', {'External Solution', 'Internal Solution', 'ND Filters'});
            
            set(parametersLayout, 'Sizes', [25 25 25 -1]);
            
            controlLayout = uiextras.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uiextras.Empty(...
                'Parent', controlLayout);
            obj.controls.beginButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Begin', ...
                'Callback', @p.onSelectedBegin);
            obj.controls.cancelButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Cancel', ...
                'Callback', @p.onSelectedClose);
            set(controlLayout, 'Sizes', [-1 75 75]);
            
            set(mainLayout, 'Sizes', [-1 25]);
            
            % Set begin button to appear as the default button.
            try %#ok<TRYNC>
                h = handle(obj.figureHandle);
                h.setDefaultButton(obj.controls.beginButton);
            end
        end
        
    end
    
end

