classdef NewExperimentView < SymphonyUI.Dialog
    
    properties
        controls
        experiment
    end
    
    methods
        
        function obj = NewExperimentView()
            obj = obj@SymphonyUI.Dialog(SymphonyUI.Presenters.NewExperimentPresenter());
        end
        
        function createInterface(obj)
            import SymphonyUI.Utilities.*;
            
            clf(obj.figureHandle);
            
            p = obj.presenter;
            
            set(obj.figureHandle, 'Name', 'New Experiment');
            set(obj.figureHandle, 'WindowStyle', 'modal');
            set(obj.figureHandle, 'WindowKeyPressFcn', @p.onWindowKeyPress);
            
            mainLayout = uiextras.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 7);
            
            parametersLayout = uiextras.VBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.nameText = uitext(layout, 'Name:');
            obj.controls.nameEdit = uicontrol( ...
                'Parent', layout, ...
                'Style', 'edit', ...
                'String', datestr(now, 'yyyy-mm-dd'), ...
                'HorizontalAlignment', 'left');
            obj.controls.nameEmpty = uiextras.Empty(...
                'Parent', layout);
            set(layout, 'Sizes', [60 -1 75]);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.locationText = uitext(layout, 'Location:');
            obj.controls.locationEdit = uicontrol( ...
                'Parent', layout, ...
                'Style', 'edit', ...
                'String', pwd, ...
                'HorizontalAlignment', 'left');
            obj.controls.locationButton = uicontrol( ...
                'Parent', layout, ...
                'Style', 'pushbutton', ...
                'String', 'Browse...', ...
                'Callback', @p.onSelectedBrowseLocation);
            set(layout, 'Sizes', [60 -1 75]);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.rigText = uitext(layout, 'Rig:');
            obj.controls.rigPopup = uicontrol( ...
                'Parent', layout, ...
                'Style', 'popupmenu', ...
                'String', {' '}, ...
                'HorizontalAlignment', 'left');
            obj.controls.rigEmpty = uiextras.Empty(...
                'Parent', layout);
            set(layout, 'Sizes', [60 -1 75]);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.purposeText = uitext(layout, 'Purpose:');
            obj.controls.purposeEdit = uicontrol( ...
                'Parent', layout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.controls.purposeEmpty = uiextras.Empty(...
                'Parent', layout);
            set(layout, 'Sizes', [60 -1 75]);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.sourcePanel = uix.Panel( ...
                'Parent', layout, ...
                'Title', 'Source', ...
                'FontName', get(obj.figureHandle, 'DefaultUicontrolFontName'), ...
                'FontSize', get(obj.figureHandle, 'DefaultUicontrolFontSize'));
            sourceLayout = uiextras.VBox( ...
                'Parent', obj.controls.sourcePanel, ...
                'Padding', 11, ...
                'Spacing', 7);
            
            set(parametersLayout, 'Sizes', [25 25 25 25 -1]);
            
            controlLayout = uiextras.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uiextras.Empty(...
                'Parent', controlLayout);
            obj.controls.openButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Open', ...
                'Callback', @p.onSelectedOpen, ...
                'KeyPressFcn', @p.onKeyPressOpen);
            obj.controls.cancelButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Cancel', ...
                'Callback', @p.onSelectedClose);
            set(controlLayout, 'Sizes', [-1 75 75]);
            
            set(mainLayout, 'Sizes', [-1 25]);
            
            % Set open button to appear as the default button.
            try %#ok<TRYNC>
                h = handle(obj.figureHandle);
                h.setDefaultButton(obj.controls.openButton);
            end
        end
        
        function n = getName(obj)
            n = get(obj.controls.nameEdit, 'String');
        end
        
        function setLocation(obj, location)
            set(obj.controls.locationEdit, 'String', location);
        end
        
        function l = getLocation(obj)
            l = get(obj.controls.locationEdit, 'String');
        end
        
        function r = getRig(obj)
            value = get(obj.controls.rigPopup, 'Value');
            string = get(obj.controls.rigPopup, 'String');
            r = string{value};
        end
        
        function p = getPurpose(obj)
            p = get(obj.controls.purposeEdit, 'String');
        end
        
    end
    
end

