classdef NewEpochGroupView < SymphonyUI.View
    
    events
        Begin
        Cancel
    end
    
    properties (Access = private)
        labelPopup
        recordingPopup
        keywordsEdit
        propertiesPanel
        externalSolutionTab
        beginButton
        cancelButton
    end
    
    methods
        
        function obj = NewEpochGroupView(parent)
            obj = obj@SymphonyUI.View(parent);
        end
        
        function createUI(obj)
            import SymphonyUI.Utilities.*;
            
            set(obj.figureHandle, 'Name', 'Begin Epoch Group');
            set(obj.figureHandle, 'Position', screenCenter(420, 320));
            
            mainLayout = uiextras.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 7);
            
            parametersLayout = uiextras.VBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            
            % Label input.
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            uiLabel(layout, 'Label:');
            obj.labelPopup = uicontrol( ...
                'Parent', layout, ...
                'Style', 'popupmenu', ...
                'String', {'Control', 'Drug', 'Wash'}, ...
                'HorizontalAlignment', 'left');
            set(layout, 'Sizes', [60 -1]);
            
            % Recording input.
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            uiLabel(layout, 'Recording:');
            obj.recordingPopup = uicontrol( ...
                'Parent', layout, ...
                'Style', 'popupmenu', ...
                'String', {'Extracellular', 'Whole-cell', 'Suction'}, ...
                'HorizontalAlignment', 'left');
            set(layout, 'Sizes', [60 -1]);
            
            % Keywords input.
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            uiLabel(layout, 'Keywords:');
            obj.keywordsEdit = uicontrol( ...
                'Parent', layout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            set(layout, 'Sizes', [60 -1]);
            
            % Properties panel.
            panel = uix.Panel( ...
                'Parent', parametersLayout, ...
                'Padding', 1);
            obj.propertiesPanel = uix.TabPanel( ...
                'Parent', panel, ...
                'TabWidth', 100, ...
                'FontName', get(obj.figureHandle, 'DefaultUicontrolFontName'), ...
                'FontSize', get(obj.figureHandle, 'DefaultUicontrolFontSize'));
            
            % External solution tab.
            layout = uiextras.HBox( ...
                'Parent', obj.propertiesPanel, ...
                'Padding', 11, ...
                'Spacing', 7, ...
                'BackgroundColor', [238/255 238/255 238/255]);
            
            vbox = uiextras.VBox( ...
                'Parent', layout, ...
                'Spacing', 3);
            uicontrol( ...
                'Parent', vbox, ...
                'Style', 'text', ...
                'String', 'Available:', ...
                'HorizontalAlignment', 'left');
            obj.externalSolutionTab.availableList = uicontrol( ...
                'Parent', vbox, ...
                'Style', 'listbox', ...
                'String', {'Ames Bicarb', 'Ames Hepes', 'NBQX-10mM', 'TPMPA-50mM'});
            set(vbox, 'Sizes', [15 -1]);
            
            vbox = uiextras.VBox( ...
                'Parent', layout);
            uiextras.Empty('Parent', vbox);
            obj.externalSolutionTab.addButton = uicontrol( ...
                'Parent', vbox, ...
                'Style', 'pushbutton', ...
                'String', '   Add->');
            obj.externalSolutionTab.removeButton = uicontrol( ...
                'Parent', vbox, ...
                'Style', 'pushbutton', ...
                'String', '<-Remove   ');
            uiextras.Empty('Parent', vbox);
            set(vbox, 'Sizes', [-1 25 25 -1]);
            
            vbox = uiextras.VBox( ...
                'Parent', layout, ...
                'Spacing', 3);
            uicontrol( ...
                'Parent', vbox, ...
                'Style', 'text', ...
                'String', 'Added:', ...
                'HorizontalAlignment', 'left');
            obj.externalSolutionTab.addedList = uicontrol( ...
                'Parent', vbox, ...
                'Style', 'listbox');
            set(vbox, 'Sizes', [15 -1]);
            
            set(layout, 'Sizes', [-1 80 -1]);
            
            % Internal solution tab.
            uiextras.Empty('Parent', obj.propertiesPanel);
            
            % ND Filters tab.
            uiextras.Empty('Parent', obj.propertiesPanel);
            
            set(obj.propertiesPanel, 'TabTitles', {'External Solution', 'Internal Solution', 'ND Filters'});
            
            set(parametersLayout, 'Sizes', [25 25 25 -1]);
            
            % Begin/Cancel controls.
            controlLayout = uiextras.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uiextras.Empty(...
                'Parent', controlLayout);
            obj.beginButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Begin', ...
                'Callback', @(h,d)notify(obj, 'Begin'));
            obj.cancelButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Cancel', ...
                'Callback', @(h,d)notify(obj, 'Cancel'));
            set(controlLayout, 'Sizes', [-1 75 75]);
            
            set(mainLayout, 'Sizes', [-1 25]);
            
            % Set begin button to appear as the default button.
            try %#ok<TRYNC>
                h = handle(obj.figureHandle);
                h.setDefaultButton(obj.beginButton);
            end
        end
        
        function l = getLabel(obj)
            l = SymphonyUI.Utilities.getSelectedPopupValue(obj.labelPopup);
        end
        
        function r = getRecording(obj)
            r = SymphonyUI.Utilities.getSelectedPopupValue(obj.recordingPopup);
        end
        
        function w = getKeywords(obj)
            w = get(obj.keywordsEdit, 'String');
        end
        
        function s = getSource(obj)
            s = [];
        end
        
    end
    
end

