classdef NewExperimentView < SymphonyUI.Dialog
    
    properties
        controls
        experiment
    end
    
    methods
        
        function obj = NewExperimentView()
            obj = obj@SymphonyUI.Dialog(SymphonyUI.Presenters.NewExperimentPresenter());
        end
        
        function createInterface(obj)
            clf(obj.figureHandle);
            
            p = obj.presenter;
            
            set(obj.figureHandle, 'Name', 'New Experiment');
            set(obj.figureHandle, 'WindowStyle', 'modal');
            set(obj.figureHandle, 'Position', [693 376 518 276]);
            
            mainLayout = uiextras.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 7);
            
            parametersLayout = uiextras.VBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.nameText = uicontrol( ...
                'Parent', layout, ...
                'Style', 'text', ...
                'String', 'Name:', ...
                'HorizontalAlignment', 'left');
            obj.controls.nameEdit = uicontrol( ...
                'Parent', layout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.controls.nameEmpty = uiextras.Empty(...
                'Parent', layout);
            set(layout, 'Sizes', [60 -1 75]);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.locationText = uicontrol( ...
                'Parent', layout, ...
                'Style', 'text', ...
                'String', 'Location:', ...
                'HorizontalAlignment', 'left');
            obj.controls.locationEdit = uicontrol( ...
                'Parent', layout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.controls.locationButton = uicontrol( ...
                'Parent', layout, ...
                'Style', 'pushbutton', ...
                'String', 'Browse...', ...
                'Callback', @p.onSelectedBrowseLocation);
            set(layout, 'Sizes', [60 -1 75]);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.rigText = uicontrol( ...
                'Parent', layout, ...
                'Style', 'text', ...
                'String', 'Rig:', ...
                'HorizontalAlignment', 'left');
            obj.controls.rigPopup = uicontrol( ...
                'Parent', layout, ...
                'Style', 'popupmenu', ...
                'String', {' '}, ...
                'HorizontalAlignment', 'left');
            obj.controls.rigEmpty = uiextras.Empty(...
                'Parent', layout);
            set(layout, 'Sizes', [60 -1 75]);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.purposeText = uicontrol( ...
                'Parent', layout, ...
                'Style', 'text', ...
                'String', 'Purpose:', ...
                'HorizontalAlignment', 'left');
            obj.controls.purposeEdit = uicontrol( ...
                'Parent', layout, ...
                'Style', 'edit', ...
                'HorizontalAlignment', 'left');
            obj.controls.purposeEmpty = uiextras.Empty(...
                'Parent', layout);
            set(layout, 'Sizes', [60 -1 75]);
            
            layout = uiextras.HBox( ...
                'Parent', parametersLayout, ...
                'Spacing', 7);
            obj.controls.sourcePanel = uix.Panel( ...
                'Parent', layout, ...
                'Title', 'Source', ...
                'FontName', get(obj.figureHandle, 'DefaultUicontrolFontName'), ...
                'FontSize', get(obj.figureHandle, 'DefaultUicontrolFontSize'));
            sourceLayout = uiextras.VBox( ...
                'Parent', obj.controls.sourcePanel, ...
                'Padding', 11, ...
                'Spacing', 7);
            layout = uiextras.HBox( ...
                'Parent', sourceLayout, ...
                'Spacing', 7);
            obj.controls.speciesText = uicontrol( ...
                'Parent', layout, ...
                'Style', 'text', ...
                'String', 'Species:', ...
                'HorizontalAlignment', 'left');
            obj.controls.speciesPopup = uicontrol( ...
                'Parent', layout, ...
                'Style', 'popupmenu', ...
                'String', {' '}, ...
                'HorizontalAlignment', 'left');
            set(layout, 'Sizes', [65 -1]);
            layout = uiextras.HBox( ...
                'Parent', sourceLayout, ...
                'Spacing', 7);
            obj.controls.phenotypeText = uicontrol( ...
                'Parent', layout, ...
                'Style', 'text', ...
                'String', 'Phenotype:', ...
                'HorizontalAlignment', 'left');
            obj.controls.phenotypePopup = uicontrol( ...
                'Parent', layout, ...
                'Style', 'popupmenu', ...
                'String', {' '}, ...
                'HorizontalAlignment', 'left');
            set(layout, 'Sizes', [65 -1]);
            set(sourceLayout, 'Sizes', [23 23]);
            
            uiextras.Empty('Parent', parametersLayout);
            
            set(parametersLayout, 'Sizes', [25 25 25 25 92 -1]);
            
            controlLayout = uiextras.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uiextras.Empty(...
                'Parent', controlLayout);
            obj.controls.openButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Open', ...
                'Callback', @p.onSelectedOpen);
            obj.controls.cancelButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Cancel', ...
                'Callback', @p.onSelectedClose);
            set(controlLayout, 'Sizes', [-1 75 75]);
            
            set(mainLayout, 'Sizes', [-1 25]);
        end
        
        function n = getName(obj)
            n = get(obj.controls.nameEdit, 'String');
        end
        
        function setLocation(obj, location)
            set(obj.controls.locationEdit, 'String', location);
        end
        
        function l = getLocation(obj)
            l = get(obj.controls.locationEdit, 'String');
        end
        
        function r = getRig(obj)
            value = get(obj.controls.rigPopup, 'Value');
            string = get(obj.controls.rigPopup, 'String');
            r = string{value};
        end
        
        function p = getPurpose(obj)
            p = get(obj.controls.purposeEdit, 'String');
        end
        
    end
    
end

