classdef ProtocolParametersView < SymphonyUI.View
    
    properties
        controls
        protocol
    end
    
    methods
        
        function obj = ProtocolParametersView()
            obj = obj@SymphonyUI.View(SymphonyUI.Presenters.ProtocolParametersPresenter());
        end
        
        function createInterface(obj)
            clf(obj.figureHandle);
            
            p = obj.presenter;
            
            set(obj.figureHandle, 'Name', 'Protocol Parameters');
            
            mainLayout = uiextras.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 7);
            
            parametersLayout = uiextras.VBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            
            controlLayout = uiextras.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uiextras.Empty(...
                'Parent', controlLayout);
            obj.controls.previewButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Preview', ...
                'Callback', @p.onSelectedPreview);
            obj.controls.applyButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Apply', ...
                'Callback', @p.onSelectedApply);
        end
        
    end
    
end

