classdef ProtocolParametersView < SymphonyUI.View
    
    events
        Apply
        Revert
        Default
    end
    
    properties (Access = private)
        applyButton
        revertButton
        defaultButton
    end
    
    methods
        
        function obj = ProtocolParametersView(parent)
            obj = obj@SymphonyUI.View(parent);
        end
        
        function createUI(obj)
            import SymphonyUI.Utilities.*;
            
            set(obj.figureHandle, 'Name', 'Protocol Parameters');
            set(obj.figureHandle, 'Position', screenCenter(518, 276));
            
            mainLayout = uiextras.VBox( ...
                'Parent', obj.figureHandle, ...
                'Padding', 11, ...
                'Spacing', 7);
            
            parametersLayout = uiextras.VBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            
            % Preview/Apply/Revert controls.
            controlLayout = uiextras.HBox( ...
                'Parent', mainLayout, ...
                'Spacing', 7);
            uiextras.Empty('Parent', controlLayout);
            obj.applyButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Apply', ...
                'Callback', @(h,d)notify(obj, 'Apply'));
            obj.revertButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Revert', ...
                'Callback', @(h,d)notify(obj, 'Revert'));
            obj.defaultButton = uicontrol( ...
                'Parent', controlLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Default', ...
                'Callback', @(h,d)notify(obj, 'Default'));
        end
        
    end
    
end

